export const ADD_SERVICE = 'ADD_SERVICE';
export const REMOVE_SERVICE = 'REMOVE_SERVICE';
export const EDIT_SERVICE = 'EDIT_SERVICE';
export const CHANGE_SERVICE_FIELD = 'CHANGE_SERVICE_FIELD';
export const RESET_SERVICE_FIELDS = 'RESET_SERVICE_FIELDS';
export const CHANGE_EDITABLE_SERVICE_FIELDS = 'CHANGE_EDITABLE_SERVICE_FIELDS';
export const DELETE_EDITABLE_SERVICE_FIELDS = 'DELETE_EDITABLE_SERVICE_FIELDS';
export const CHANGE_FILTER_FIELD = 'CHANGE_FILTER_FIELD';